[package]
name = "brasileirao"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.42.0", features = ["full"] }
serde = "1.0.217"
serde_derive = "1.0.217"
colored = "2"